### ISSUE TITLE
Download tracking at the per-sample level

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#189]
### New Issue Checklist
- [x] The title is short and descriptive
- [x] The issue contains an:
  - [x] Idea (new feature, user story, etc)
  - [ ] Problem
- [x] You have explained the:
  - [x] Context
  - [x] Problem or idea
  - [x] Solution or next step

### Context

Liz asked if we would be able to keep track of the pieces of data that people use from refine.bio. I can see why this would be useful in describing the impact of this investment.

### Problem or idea

It would be helpful to be able to track how many times each sample is downloaded.

### Solution or next step

We should consider the places where a sample can be obtained and make sure that they track the number of uses.

**Comment by kurtwheeler** [comment]
Seems like we could add a column `num_downloads` to the `samples` table to keep track of this and then add an endpoint to increment it. Then its just a matter of making sure that we hit that endpoint from everywhere we allow people to download samples like you said.

**Comment by Miserlou** [comment]
We can get all of this information from the Dataset objects themselves, so we can look at those when we generate summary reports.
