### ISSUE TITLE
The improved issue template is confusing

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio#191]
### New Issue Checklist

- [x] The title is short and descriptive
- [x] The issue contains an:
  - [ ] Idea (new feature, user story, etc)
  - [x] Problem
- [x] You have explained the:
  - [x] Context
  - [x] Problem or idea
  - [x] Solution or next step

### Context

I was creating new issues this morning. As I was filling things out, I found the new template jarring.

### Problem or idea

The context seems like it should come before the problem. Also, the checklist that is supposed to be used to make sure the issue is reasonably complete is commented out.

### Solution or next step

I'd propose that we revert the portions of https://github.com/AlexsLemonade/refinebio/pull/137 that change the checklist.

**Comment by jaclyn-taroni** [comment]
I agree

**Comment by Miserlou** [comment]
I don't like having to read everybody else's checklist for every new ticket. It's up to you to do file a proper ticket, it's not up to people who actually work on tickets to have to read somebody else's checklist of things that should be done anyway every time.

![beautiful-classic-bike-shed-wajaohy-](https://user-images.githubusercontent.com/139987/38472416-bd8e549c-3b4d-11e8-8c8f-4f9e7ba7f0a8.jpg)

**Comment by cgreene** [comment]
There were two changes.

* One puts `context` before `problem`.
* The other is the commenting out of the checklist.

As someone who files tickets, we'll get better ones if the template works for people. Asking for context before asking for the problem seems like the natural ordering.

Also, giving people a checklist can be a handy way to go about getting better tickets. It also helps to quickly triage bad tickets. Someone who didn't fill out the checklist probably also didn't do the other things that make a ticket useful.

**Comment by cgreene** [comment]
Yea - the GitHub -> ToDo is suboptimal there. I think our checklist that is not a checklist can be converted to a checklist that is a checklist. 😄

**Comment by kurtwheeler** [comment]
What's the status on this? I'm happy to make the requested changes if needed.

After thinking about this for a week though I think I agree that the context should come first and I also feel that the checklist is kinda annoying to have on all the issues. I understand that the goal of it is to get better tickets, but I think having the rest of the template might be enough if we include a commented out line in the template along the lines of:

> Please make sure the title of this issue is short and descriptive, that the issue contains  a problem or an idea (new feature, user story, etc), and that you have filled out each of the following sections.

I think that will remind people about the things we care about. Also I'm not sure I agree that the checklist makes it easier to triage bad tickets. I think we can just as easily visibly check that each of the sections has something in it as we can check that the corresponding checkboxes have been filled out.

There's a few things I find annoying about the checklist, but this is one that hasn't been brought up yet:

![image](https://user-images.githubusercontent.com/4026833/38817657-d020a7da-4166-11e8-8cad-ddc21fe54b4d.png)

**Comment by cgreene** [comment]
On my plate. Will aim to do it today.
